name: FTP Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build

    - name: Archive build folder
      run: cd build && tar -cvf ../front.tar . && cd ..

    - name: Copy to remote server
      uses: appleboy/scp-action@master
      with:
        host: loopitis.com
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "./front.tar"
        target: "~/visual"

    - name: Execute command on remote server
      uses: appleboy/ssh-action@master
      with:
        host: loopitis.com
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: cd visual && docker-compose --env-file config.properties build visual_front && docker-compose --env-file config.properties up -d visual_front